import { Col, Row, Typography } from 'antd';
import 'antd/dist/antd.css';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from './index.module.less';

const { Title, Text } = Typography;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Website - homepage</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.hero}>
        <Image
          src='/garden.jpg'
          layout='fill'
          objectFit='cover'
          objectPosition='right'
        />
        <Row justify='center' align='middle'>
          <Col xs={22} md={20} lg={18} xl={16}>
            <Title>John Doe</Title>
            <Text>Gardening &amp; mowing</Text>
          </Col>
        </Row>
      </div>
    </>
  );
};

export default Home;
